### ISSUE TITLE
Implement configurable storage location

### ISSUE THREAD

**Issue by ruqqq** [cs2103jan2015-t09-1j/main#103]
User Story #12.

2 tasks:

Add command to change storage location:
1. i.e. change-storage storage.txt
2. Copy current storage to new storage file
3. Create omnitask.conf file and save the new file name inside this file
4. Return success if nothing fails

In Controller, when init-ing Data:
1. Open omnitask.conf if exist
2. Read the file to get the storage location
3. If does not exist or fail (corrupt/invalid file), default to "storage.txt"

**Comment by wksim91** [comment]
I looked into this the other day on stackoverflow and this is what I've found

File file = new File("Z:\results\results.txt");

Probably can make the File(parameter) parameter ("Z:\results...." in the above code segment") customised by user input, else default is... default.

\ = \ in java because \ itself is an escape char. 

Hope this helps.
