### ISSUE TITLE
V0.3 To-Do

### ISSUE THREAD

**Issue by wksim91** [cs2103jan2015-t09-1j/main#68]
V0.3 To-Do list:
1. Implement Undo function (Redo if possible)
2. Clean up migrated codes from previous architecture (esp CRUD)
3. Parser to detect remaining attributes (priority, recurrence?)
4. Obvious bug testing (making sure all inputs are valid, output makes sense)
5. UI design (maybe)

This is what I think we can achieve for V0.3 as of now. (V0.3 is scheduled for release this Sunday, 29 March.)

...and we need to update Dev Guide to the new architecture too. Please provide the relevant diagrams if possible. I will try and work on the parts that the tutor pointed out (not enough context etc etc... Zzz)

**Comment by ruqqq** [comment]
@wksim91 Should we do .clone() for every object return by Data class? So that any modification on the task object does not directly modify the tasks cache in Data class.

Do note however that .clone() does not do a deep copy (it'll only copy primitives).

Other things on top of my mind that has to be done:
- Rename packages to be more logical (i.e. Data class actually should be under package model. And our current classes in package model should probably be under another package called object or item?); For readability
- Add Javadoc comments so we can autogenerate API documentation: http://www.oracle.com/technetwork/articles/java/index-137868.html

**Comment by ruqqq** [comment]
Can we check this checklist so we can check what's done/not done and create issues for V0.4? @wksim91 @tlx2103 @ChenSijie
